//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class unitworksccsEntities : DbContext
    {
        public unitworksccsEntities()
            : base("name=unitworksccsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alarm_history_master> alarm_history_master { get; set; }
        public virtual DbSet<configuration_tblpmchecklist> configuration_tblpmchecklist { get; set; }
        public virtual DbSet<configuration_tblpmcheckpoint> configuration_tblpmcheckpoint { get; set; }
        public virtual DbSet<configuration_tblprimitivemaintainancescheduling> configuration_tblprimitivemaintainancescheduling { get; set; }
        public virtual DbSet<configuration_tblsensorgroup> configuration_tblsensorgroup { get; set; }
        public virtual DbSet<configurationtblmachinesensor> configurationtblmachinesensors { get; set; }
        public virtual DbSet<configurationtblsensordatalink> configurationtblsensordatalinks { get; set; }
        public virtual DbSet<configurationtblsensormaster> configurationtblsensormasters { get; set; }
        public virtual DbSet<DocumentUploaderMaster> DocumentUploaderMasters { get; set; }
        public virtual DbSet<frommail> frommails { get; set; }
        public virtual DbSet<handle_no_ping> handle_no_ping { get; set; }
        public virtual DbSet<IOTGatwayPacketsData> IOTGatwayPacketsDatas { get; set; }
        public virtual DbSet<jobcard_details> jobcard_details { get; set; }
        public virtual DbSet<loginTrackerDetail> loginTrackerDetails { get; set; }
        public virtual DbSet<machineDetailsWimerasy> machineDetailsWimerasys { get; set; }
        public virtual DbSet<mailmaster> mailmasters { get; set; }
        public virtual DbSet<message_code_master> message_code_master { get; set; }
        public virtual DbSet<message_history_master> message_history_master { get; set; }
        public virtual DbSet<monthdata> monthdatas { get; set; }
        public virtual DbSet<operationlog> operationlogs { get; set; }
        public virtual DbSet<parameter_sendor_data> parameter_sendor_data { get; set; }
        public virtual DbSet<parameter_sensor_data_current> parameter_sensor_data_current { get; set; }
        public virtual DbSet<parameter_sensor_data_level> parameter_sensor_data_level { get; set; }
        public virtual DbSet<parameter_sensor_data_pressure> parameter_sensor_data_pressure { get; set; }
        public virtual DbSet<parameter_sensor_data_temperature> parameter_sensor_data_temperature { get; set; }
        public virtual DbSet<parameter_tool_data> parameter_tool_data { get; set; }
        public virtual DbSet<parameter> parameters { get; set; }
        public virtual DbSet<parameters_master> parameters_master { get; set; }
        public virtual DbSet<pcb_details> pcb_details { get; set; }
        public virtual DbSet<pcb_parameters> pcb_parameters { get; set; }
        public virtual DbSet<pcbdaq> pcbdaqs { get; set; }
        public virtual DbSet<pcbdaqin_tbl> pcbdaqin_tbl { get; set; }
        public virtual DbSet<pcbdps_master> pcbdps_master { get; set; }
        public virtual DbSet<PINGHANDLER_tbl> PINGHANDLER_tbl { get; set; }
        public virtual DbSet<program_execution_master> program_execution_master { get; set; }
        public virtual DbSet<program_master> program_master { get; set; }
        public virtual DbSet<sapFileGeneratedDetail> sapFileGeneratedDetails { get; set; }
        public virtual DbSet<sharathtable> sharathtables { get; set; }
        public virtual DbSet<smtpdetail> smtpdetails { get; set; }
        public virtual DbSet<tbl_autoreport_log> tbl_autoreport_log { get; set; }
        public virtual DbSet<tbl_autoreportbasedon> tbl_autoreportbasedon { get; set; }
        public virtual DbSet<tbl_autoreportsetting> tbl_autoreportsetting { get; set; }
        public virtual DbSet<tbl_autoreporttime> tbl_autoreporttime { get; set; }
        public virtual DbSet<tbl_axisdet> tbl_axisdet { get; set; }
        public virtual DbSet<tbl_axisdetails1> tbl_axisdetails1 { get; set; }
        public virtual DbSet<tbl_axisdetails2> tbl_axisdetails2 { get; set; }
        public virtual DbSet<tbl_CategoryNames> tbl_CategoryNames { get; set; }
        public virtual DbSet<tbl_CheckListMachines> tbl_CheckListMachines { get; set; }
        public virtual DbSet<tbl_CycleTimeAnalysis> tbl_CycleTimeAnalysis { get; set; }
        public virtual DbSet<tbl_deletedProgDet> tbl_deletedProgDet { get; set; }
        public virtual DbSet<tbl_genericfilepath> tbl_genericfilepath { get; set; }
        public virtual DbSet<tbl_livecbmparameters> tbl_livecbmparameters { get; set; }
        public virtual DbSet<tbl_MachineMakeDetails> tbl_MachineMakeDetails { get; set; }
        public virtual DbSet<tbl_OEEDetails> tbl_OEEDetails { get; set; }
        public virtual DbSet<tbl_OEEOperatorDetails> tbl_OEEOperatorDetails { get; set; }
        public virtual DbSet<tbl_oeereportasdivision> tbl_oeereportasdivision { get; set; }
        public virtual DbSet<tbl_OEEShiftDetails> tbl_OEEShiftDetails { get; set; }
        public virtual DbSet<tbl_PMSDashboardCheckList> tbl_PMSDashboardCheckList { get; set; }
        public virtual DbSet<tbl_ProdAndonDisp> tbl_ProdAndonDisp { get; set; }
        public virtual DbSet<tbl_ProdManMachine> tbl_ProdManMachine { get; set; }
        public virtual DbSet<tbl_ProdOrderLosses> tbl_ProdOrderLosses { get; set; }
        public virtual DbSet<tbl_reportmaster> tbl_reportmaster { get; set; }
        public virtual DbSet<tbl_SaveNCProgVer> tbl_SaveNCProgVer { get; set; }
        public virtual DbSet<tbl_ScreenPagesDetails> tbl_ScreenPagesDetails { get; set; }
        public virtual DbSet<tbl_servodetails> tbl_servodetails { get; set; }
        public virtual DbSet<tbl_UtilReport> tbl_UtilReport { get; set; }
        public virtual DbSet<tblactivitylog> tblactivitylogs { get; set; }
        public virtual DbSet<tblAndonDispDet> tblAndonDispDets { get; set; }
        public virtual DbSet<tblAndonImageTextScheduledDisplay> tblAndonImageTextScheduledDisplays { get; set; }
        public virtual DbSet<tblapp_paths> tblapp_paths { get; set; }
        public virtual DbSet<tblatccounter> tblatccounters { get; set; }
        public virtual DbSet<tblBookStock> tblBookStocks { get; set; }
        public virtual DbSet<tblbottelneck> tblbottelnecks { get; set; }
        public virtual DbSet<tblbreakdown> tblbreakdowns { get; set; }
        public virtual DbSet<tblBreakDown_ReportDetails> tblBreakDown_ReportDetails { get; set; }
        public virtual DbSet<tblBreakdowncode> tblBreakdowncodes { get; set; }
        public virtual DbSet<tblBreakDownTickect> tblBreakDownTickects { get; set; }
        public virtual DbSet<tblBusinessDetail> tblBusinessDetails { get; set; }
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblCategoryDetail> tblCategoryDetails { get; set; }
        public virtual DbSet<tblCategoryMaster> tblCategoryMasters { get; set; }
        public virtual DbSet<tblcell> tblcells { get; set; }
        public virtual DbSet<tblCellFinalMaster> tblCellFinalMasters { get; set; }
        public virtual DbSet<tblcellpart> tblcellparts { get; set; }
        public virtual DbSet<tblCheckList_Details> tblCheckList_Details { get; set; }
        public virtual DbSet<tblCheckList_Header> tblCheckList_Header { get; set; }
        public virtual DbSet<tblChildFgPartNo> tblChildFgPartNoes { get; set; }
        public virtual DbSet<tblClassMaster> tblClassMasters { get; set; }
        public virtual DbSet<tblControlPlan> tblControlPlans { get; set; }
        public virtual DbSet<tblControlPlanDetail> tblControlPlanDetails { get; set; }
        public virtual DbSet<tblcustomer> tblcustomers { get; set; }
        public virtual DbSet<tbldailyprodstatu> tbldailyprodstatus { get; set; }
        public virtual DbSet<tbldaytiming> tbldaytimings { get; set; }
        public virtual DbSet<tblDefectCodeMaster> tblDefectCodeMasters { get; set; }
        public virtual DbSet<tblDepartmentDetail> tblDepartmentDetails { get; set; }
        public virtual DbSet<tblDirLineInspector> tblDirLineInspectors { get; set; }
        public virtual DbSet<tblDirQualityHead> tblDirQualityHeads { get; set; }
        public virtual DbSet<tbldowntimecategory> tbldowntimecategories { get; set; }
        public virtual DbSet<tbldowntimedetail> tbldowntimedetails { get; set; }
        public virtual DbSet<tblDryRun> tblDryRuns { get; set; }
        public virtual DbSet<tblemailescalation> tblemailescalations { get; set; }
        public virtual DbSet<tblEmployeeShiftDetail> tblEmployeeShiftDetails { get; set; }
        public virtual DbSet<tblendcode> tblendcodes { get; set; }
        public virtual DbSet<tblescalationlog> tblescalationlogs { get; set; }
        public virtual DbSet<tblEscalationMatrix> tblEscalationMatrices { get; set; }
        public virtual DbSet<tblEscalationPriorityDetail> tblEscalationPriorityDetails { get; set; }
        public virtual DbSet<tblEscalationTiming> tblEscalationTimings { get; set; }
        public virtual DbSet<tblFgAndCellAllocation> tblFgAndCellAllocations { get; set; }
        public virtual DbSet<tblFgPartNoDet> tblFgPartNoDets { get; set; }
        public virtual DbSet<tblGeneralDefectCode> tblGeneralDefectCodes { get; set; }
        public virtual DbSet<tblgenericworkcode> tblgenericworkcodes { get; set; }
        public virtual DbSet<tblgenericworkentry> tblgenericworkentries { get; set; }
        public virtual DbSet<tblhistpm> tblhistpms { get; set; }
        public virtual DbSet<tblholdcode> tblholdcodes { get; set; }
        public virtual DbSet<tblHolidayManagment> tblHolidayManagments { get; set; }
        public virtual DbSet<tblholiday> tblholidays { get; set; }
        public virtual DbSet<tblHolidayTypeMaster> tblHolidayTypeMasters { get; set; }
        public virtual DbSet<tblIpAddress> tblIpAddresses { get; set; }
        public virtual DbSet<tblIssuedReceived> tblIssuedReceiveds { get; set; }
        public virtual DbSet<tbllivedailyprodstatu> tbllivedailyprodstatus { get; set; }
        public virtual DbSet<tbllivemode> tbllivemodes { get; set; }
        public virtual DbSet<tbllossescode> tbllossescodes { get; set; }
        public virtual DbSet<tbllossofentry> tbllossofentries { get; set; }
        public virtual DbSet<tblmachineaxisdetail> tblmachineaxisdetails { get; set; }
        public virtual DbSet<tblmachinecategory> tblmachinecategories { get; set; }
        public virtual DbSet<tblMachineCategoryName> tblMachineCategoryNames { get; set; }
        public virtual DbSet<tblmachinedetail> tblmachinedetails { get; set; }
        public virtual DbSet<tblmailid> tblmailids { get; set; }
        public virtual DbSet<tblmasterparts_st_sw> tblmasterparts_st_sw { get; set; }
        public virtual DbSet<tblMasterValue> tblMasterValues { get; set; }
        public virtual DbSet<tblMaterialMaster> tblMaterialMasters { get; set; }
        public virtual DbSet<tblmimic> tblmimics { get; set; }
        public virtual DbSet<tblmode> tblmodes { get; set; }
        public virtual DbSet<tblmodetemp> tblmodetemps { get; set; }
        public virtual DbSet<tblmodulehelper> tblmodulehelpers { get; set; }
        public virtual DbSet<tblmodulemaster> tblmodulemasters { get; set; }
        public virtual DbSet<tblmodule> tblmodules { get; set; }
        public virtual DbSet<tblmultipleworkorder> tblmultipleworkorders { get; set; }
        public virtual DbSet<tblNcProgramTransferMain> tblNcProgramTransferMains { get; set; }
        public virtual DbSet<tblNoOfAxi> tblNoOfAxis { get; set; }
        public virtual DbSet<tbloeedashboardfinalvariable> tbloeedashboardfinalvariables { get; set; }
        public virtual DbSet<tbloeedashboardvariable> tbloeedashboardvariables { get; set; }
        public virtual DbSet<tbloeedashboardvariablestoday> tbloeedashboardvariablestodays { get; set; }
        public virtual DbSet<tblOperatorDashboard> tblOperatorDashboards { get; set; }
        public virtual DbSet<tblOperatorDetail> tblOperatorDetails { get; set; }
        public virtual DbSet<tblOperatorHeader> tblOperatorHeaders { get; set; }
        public virtual DbSet<tblOperatorLoginDetail> tblOperatorLoginDetails { get; set; }
        public virtual DbSet<tblOperatorMachineDetail> tblOperatorMachineDetails { get; set; }
        public virtual DbSet<tblPallet> tblPallets { get; set; }
        public virtual DbSet<tblpartlearningreport> tblpartlearningreports { get; set; }
        public virtual DbSet<tblpart> tblparts { get; set; }
        public virtual DbSet<tblpartscountandcutting> tblpartscountandcuttings { get; set; }
        public virtual DbSet<tblpir> tblpirs { get; set; }
        public virtual DbSet<tblpirminmax> tblpirminmaxes { get; set; }
        public virtual DbSet<tblPlanLinkageMaster> tblPlanLinkageMasters { get; set; }
        public virtual DbSet<tblplannedbreak> tblplannedbreaks { get; set; }
        public virtual DbSet<tblplant> tblplants { get; set; }
        public virtual DbSet<tblpmsdetail> tblpmsdetails { get; set; }
        public virtual DbSet<tblPrecentColour> tblPrecentColours { get; set; }
        public virtual DbSet<tblPresentTool> tblPresentTools { get; set; }
        public virtual DbSet<tblpriorityalarm> tblpriorityalarms { get; set; }
        public virtual DbSet<tblProcess> tblProcesses { get; set; }
        public virtual DbSet<tblProdPlanMaster> tblProdPlanMasters { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
        public virtual DbSet<tblProductWiseDefectCode> tblProductWiseDefectCodes { get; set; }
        public virtual DbSet<tblprogramtransferhistory> tblprogramtransferhistories { get; set; }
        public virtual DbSet<tblRaisedTicket> tblRaisedTickets { get; set; }
        public virtual DbSet<tblRejectionDetail> tblRejectionDetails { get; set; }
        public virtual DbSet<tblrejectqty> tblrejectqties { get; set; }
        public virtual DbSet<tblrejectreason> tblrejectreasons { get; set; }
        public virtual DbSet<tblreportholder> tblreportholders { get; set; }
        public virtual DbSet<tblReworkDetail> tblReworkDetails { get; set; }
        public virtual DbSet<tblReworkReason> tblReworkReasons { get; set; }
        public virtual DbSet<tblrolemodulelink> tblrolemodulelinks { get; set; }
        public virtual DbSet<tblrole> tblroles { get; set; }
        public virtual DbSet<tblRoutingNo> tblRoutingNoes { get; set; }
        public virtual DbSet<tblSAPInput> tblSAPInputs { get; set; }
        public virtual DbSet<tblSar> tblSars { get; set; }
        public virtual DbSet<tblSarminmax> tblSarminmaxes { get; set; }
        public virtual DbSet<tblsendermailid> tblsendermailids { get; set; }
        public virtual DbSet<tblSetupMaint> tblSetupMaints { get; set; }
        public virtual DbSet<tblshift_breaks> tblshift_breaks { get; set; }
        public virtual DbSet<tblshift_mstr> tblshift_mstr { get; set; }
        public virtual DbSet<tblshiftdetail> tblshiftdetails { get; set; }
        public virtual DbSet<tblshiftdetails_machinewise> tblshiftdetails_machinewise { get; set; }
        public virtual DbSet<tblshiftmethod> tblshiftmethods { get; set; }
        public virtual DbSet<tblshiftplanner> tblshiftplanners { get; set; }
        public virtual DbSet<tblshop> tblshops { get; set; }
        public virtual DbSet<tblSmsDetail> tblSmsDetails { get; set; }
        public virtual DbSet<tblSourceMaster> tblSourceMasters { get; set; }
        public virtual DbSet<tblStatusMaster> tblStatusMasters { get; set; }
        public virtual DbSet<tblStdToolLife> tblStdToolLives { get; set; }
        public virtual DbSet<tblStoppage> tblStoppages { get; set; }
        public virtual DbSet<tblSubCellFinalMaster> tblSubCellFinalMasters { get; set; }
        public virtual DbSet<tblSystemConfig> tblSystemConfigs { get; set; }
        public virtual DbSet<tblTallStockAvailibility> tblTallStockAvailibilities { get; set; }
        public virtual DbSet<tblTicketRaisedDet> tblTicketRaisedDets { get; set; }
        public virtual DbSet<tblTicketReason> tblTicketReasons { get; set; }
        public virtual DbSet<tblToolAndSocketDetail> tblToolAndSocketDetails { get; set; }
        public virtual DbSet<tblToolBrDnReasonLvl1> tblToolBrDnReasonLvl1 { get; set; }
        public virtual DbSet<tblToolBrkDnReason> tblToolBrkDnReasons { get; set; }
        public virtual DbSet<tblToolCounter> tblToolCounters { get; set; }
        public virtual DbSet<tbltoollifeoperator> tbltoollifeoperators { get; set; }
        public virtual DbSet<tblTool> tblTools { get; set; }
        public virtual DbSet<tbltosapfilepath> tbltosapfilepaths { get; set; }
        public virtual DbSet<tbltosapshopname> tbltosapshopnames { get; set; }
        public virtual DbSet<tblTrialPartCount> tblTrialPartCounts { get; set; }
        public virtual DbSet<tblunit> tblunits { get; set; }
        public virtual DbSet<tbluser> tblusers { get; set; }
        public virtual DbSet<tblwolossess> tblwolossesses { get; set; }
        public virtual DbSet<tblworeport> tblworeports { get; set; }
        public virtual DbSet<tblWorkCenter> tblWorkCenters { get; set; }
        public virtual DbSet<tblworkorderentry> tblworkorderentries { get; set; }
        public virtual DbSet<weekdata> weekdatas { get; set; }
        public virtual DbSet<ControlPlan> ControlPlans { get; set; }
        public virtual DbSet<cpDetail> cpDetails { get; set; }
        public virtual DbSet<DIR> DIRs { get; set; }
        public virtual DbSet<document> documents { get; set; }
        public virtual DbSet<employeeDetail> employeeDetails { get; set; }
        public virtual DbSet<Evaluation> Evaluations { get; set; }
        public virtual DbSet<fgAndCellAllocationDetail> fgAndCellAllocationDetails { get; set; }
        public virtual DbSet<Process> Processes { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<productWiseDefectDetail> productWiseDefectDetails { get; set; }
        public virtual DbSet<revisionDetail> revisionDetails { get; set; }
        public virtual DbSet<SCC> SCCs { get; set; }
        public virtual DbSet<shift_master> shift_master { get; set; }
        public virtual DbSet<tbl_livecbmdetails> tbl_livecbmdetails { get; set; }
        public virtual DbSet<tbl_livetblsensorvalue> tbl_livetblsensorvalue { get; set; }
        public virtual DbSet<tblAndonDisplayRotate> tblAndonDisplayRotates { get; set; }
    }
}
