//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class parameter_sendor_data
    {
        public int parameterSensorDataId { get; set; }
        public Nullable<int> machineId { get; set; }
        public Nullable<System.DateTime> sensorDataCapturedTime { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<System.DateTime> correctedDate { get; set; }
    }
}
