//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sapFileGeneratedDetail
    {
        public long sapFileGeneratedId { get; set; }
        public Nullable<System.DateTime> sapFileGeneratedDate { get; set; }
        public Nullable<int> sapFileGeneratedHour { get; set; }
        public Nullable<long> TotalCountOfRows { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string sapFileNameGenerated { get; set; }
    }
}
